name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Add $GOPATH/bin to $PATH
        run: echo ::set-env name=PATH::$(echo $PATH:$GOPATH/bin)

      - name: Install ginkgo
        run: go get github.com/onsi/ginkgo/ginkgo

      - name: Test all
        run: make test
